version: '3.8'

services:
  auth:
    build:
      context: .
      dockerfile: services/auth/Dockerfile.dev
    ports:
      - "8081:8081"
    env_file:
      - services/auth/.env
    volumes:
      - ./services/auth:/app
      - auth_go_mod:/go/pkg/mod
    depends_on:
      - postgres
      - redis
    networks:
      - app-network
    environment:
      - GIN_MODE=debug
      - GO_ENV=development

  gateway:
    build:
      context: .
      dockerfile: services/gateway/Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - services/gateway/.env
    depends_on:
      - auth
    networks:
      - app-network

  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=minisapi_auth
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network

volumes:
  postgres_data:
  redis_data:
  auth_go_mod:

networks:
  app-network:
    driver: bridge 