global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'auth_service'
    static_configs:
      - targets: ['auth:8081']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'gateway-service'
    static_configs:
      - targets: ['gateway:8080'] 